Disable publishing from generic linux image
```
HTTPError: 400 Client Error: Binary wheel 'restrained_ESP_fit-2.4.8-cp37-cp37m-linux_x86_64.whl' has an unsupported platform tag 'linux_x86_64'. for url: https://test.pypi.org/legacy/
```

We'll need to use the manylinux image